print(type('Hello world'))
print(type(20))
print(type(20.5))
print(type(1j))
print(type(['apple', 'orange']))
print(type(('apple', 'orange')))
print(type(range(6)))
print(type({ "name": "Li Quang Tien"}))
print(type({ "apple", "cherry", "tangerine"}))
print(type(frozenset({ "apple", "cheery", "tangerine"})))
print(type(True))
print(type(b"LI QUANG TIEN"))
print(type(bytearray(10)))
print(type(memoryview(bytes(5))))
print(type(None))
